services:
  postgres:
    image: postgres:16
    restart: always
    container_name: circuit-db
    environment:
      POSTGRES_DB: circuitdb
      POSTGRES_USER: circuit
      POSTGRES_PASSWORD: circuit123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
