spring.application.name=circuit-simulator
spring.datasource.url=jdbc:postgresql://localhost:5432/circuitdb
spring.datasource.username=circuit
spring.datasource.password=circuit123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
