/** Kit inventory shown on /kit — quantities match the learning-kit parts list. */

export const KIT_CATEGORIES = [
    {
        id: 'board',
        accent: '#43d9a2',
        titleKa: 'სამუშაო დაფა',
        titleEn: 'Baseboard',
        descKa: 'წრედების ასაწყობი სამუშაო დაფა — დეტალები წკაპებით იდგმება ბადეზე.',
        descEn: 'Snap baseboard for assembling circuits — parts mount on the labeled grid.',
        featured: true,
        items: [
            {
                id: 'board',
                image: '/components/board.svg',
                nameKa: 'წრედების ასაწყობი სამუშაო დაფა',
                nameEn: 'Circuit assembly baseboard',
                qty: 1,
            },
        ],
    },
    {
        id: 'wires',
        accent: '#60c5f1',
        titleKa: 'გამტარები',
        titleEn: 'Conductors',
        descKa: 'გამოიყენება დეტალების ერთმანეთთან დასაკავშირებლად.',
        descEn: 'Used to connect parts to each other on the board.',
        items: [
            {
                id: 'c2',
                image: '/components/connector2.svg',
                nameKa: '2 კონტაქტიანი გამტარი',
                nameEn: '2-contact conductor',
                qty: 12,
            },
            {
                id: 'c3',
                image: '/components/connector3.svg',
                nameKa: '3 კონტაქტიანი გამტარი',
                nameEn: '3-contact conductor',
                qty: 6,
            },
            {
                id: 'c4',
                image: '/components/connector4.svg',
                nameKa: '4 კონტაქტიანი გამტარი',
                nameEn: '4-contact conductor',
                qty: 4,
            },
            {
                id: 'c5',
                image: '/components/connector5.svg',
                nameKa: '5 კონტაქტიანი გამტარი',
                nameEn: '5-contact conductor',
                qty: 2,
            },
            {
                id: 'c6',
                image: '/components/connector6.svg',
                nameKa: '6 კონტაქტიანი გამტარი',
                nameEn: '6-contact conductor',
                qty: 1,
            },
            {
                id: 'c7',
                image: '/components/connector7.svg',
                nameKa: '7 კონტაქტიანი გამტარი',
                nameEn: '7-contact conductor',
                qty: 1,
            },
            {
                id: 'soft',
                images: [
                    '/components/wire-pin-red.svg',
                    '/components/wire-pin-black.svg',
                ],
                nameKa: '2 კონტაქტიანი რბილი გამტარი',
                nameEn: '2-contact soft wire',
                qty: 4,
            },
        ],
    },
    {
        id: 'power',
        accent: '#ffd166',
        titleKa: 'კვება და ჩამრთველები',
        titleEn: 'Power & switches',
        descKa: 'კვების წყაროები და წრედის ჩართვა–გამორთვის დეტალები.',
        descEn: 'Power packs and parts that open or close the circuit.',
        items: [
            {
                id: 'ps',
                image: '/components/power-supply.svg',
                nameKa: 'კვების წყარო',
                nameEn: 'Power supply',
                qty: 2,
            },
            {
                id: 'sw',
                image: '/components/switch.svg',
                nameKa: 'ჩამრთველი',
                nameEn: 'Switch',
                badge: '#60c5f1',
            },
            {
                id: 'btn',
                image: '/components/button.svg',
                nameKa: 'ღილაკი',
                nameEn: 'Button',
                qty: 2,
                badge: '#60c5f1',
            },
            {
                id: 'slide',
                image: '/components/slide-switch-ab.svg',
                nameKa: 'გადამრთველი (SPDT)',
                nameEn: 'Slide switch (SPDT)',
                qty: 2,
            },
        ],
    },
    {
        id: 'resistors',
        accent: '#f5d76e',
        titleKa: 'რეზისტორები',
        titleEn: 'Resistors',
        descKa: 'მუდმივი და ცვალებადი რეზისტორები დენისა და ძაბვის დასარეგულირებლად.',
        descEn: 'Fixed and variable resistors for controlling current and voltage.',
        items: [
            {
                id: 'r20',
                image: '/components/resistor-20o.svg',
                nameKa: 'რეზისტორი 20 Ω',
                nameEn: 'Resistor 20 Ω',
                qty: 2,
            },
            {
                id: 'r100',
                image: '/components/resistor-100o.svg',
                nameKa: 'რეზისტორი 100 Ω',
                nameEn: 'Resistor 100 Ω',
                qty: 2,
            },
            {
                id: 'r1k',
                image: '/components/resistor-1ko.svg',
                nameKa: 'რეზისტორი 1 kΩ',
                nameEn: 'Resistor 1 kΩ',
                qty: 4,
            },
            {
                id: 'r5k1',
                image: '/components/resistor-5ko1.svg',
                nameKa: 'რეზისტორი 5.1 kΩ',
                nameEn: 'Resistor 5.1 kΩ',
                qty: 2,
            },
            {
                id: 'r10k',
                image: '/components/resistor-10ko.svg',
                nameKa: 'რეზისტორი 10 kΩ',
                nameEn: 'Resistor 10 kΩ',
                qty: 2,
            },
            {
                id: 'r100k',
                image: '/components/resistor-100ko.svg',
                nameKa: 'რეზისტორი 100 kΩ',
                nameEn: 'Resistor 100 kΩ',
                qty: 2,
            },
            {
                id: 'r510k',
                image: '/components/resistor-510ko.svg',
                nameKa: 'რეზისტორი 510 kΩ',
                nameEn: 'Resistor 510 kΩ',
                qty: 2,
            },
            {
                id: 'pot',
                image: '/components/var-resistor-10k.svg',
                nameKa: 'ცვლადი რეზისტორი 10 kΩ',
                nameEn: 'Variable resistor 10 kΩ',
                qty: 2,
            },
            {
                id: 'photo',
                image: '/components/photo-resistor.svg',
                nameKa: 'ფოტორეზისტორი',
                nameEn: 'Photoresistor',
                qty: 1,
            },
        ],
    },
    {
        id: 'caps',
        accent: '#43d9a2',
        titleKa: 'კონდენსატორები',
        titleEn: 'Capacitors',
        descKa: 'დამუხტვა–განმუხტვის და დროითი ეფექტების დეტალები.',
        descEn: 'Parts for charge/discharge and timing effects.',
        items: [
            {
                id: 'c1uf',
                image: '/components/capacitor-1uf.svg',
                nameKa: 'კონდენსატორი 1 µF',
                nameEn: 'Capacitor 1 µF',
                qty: 2,
            },
            {
                id: 'c10uf',
                image: '/components/capacitor-10uf.svg',
                nameKa: 'კონდენსატორი 10 µF',
                nameEn: 'Capacitor 10 µF',
                qty: 2,
            },
            {
                id: 'c100uf',
                image: '/components/capacitor-100uf.svg',
                nameKa: 'კონდენსატორი 100 µF',
                nameEn: 'Capacitor 100 µF',
                qty: 2,
            },
            {
                id: 'c470uf',
                image: '/components/capacitor-470uf.svg',
                nameKa: 'კონდენსატორი 470 µF',
                nameEn: 'Capacitor 470 µF',
                qty: 2,
            },
        ],
    },
    {
        id: 'semi',
        accent: '#f78fb3',
        titleKa: 'ნახევარგამტარები',
        titleEn: 'Semiconductors',
        descKa: 'დიოდები, შუქდიოდები და ტრანზისტორები.',
        descEn: 'Diodes, LEDs, and transistors.',
        items: [
            {
                id: 'diode',
                image: '/components/diode.svg',
                nameKa: 'დიოდი',
                nameEn: 'Diode',
                qty: 2,
                badge: '#f5d76e',
            },
            {
                id: 'ledr',
                image: '/components/led-red.svg',
                nameKa: 'წითელი შუქდიოდი',
                nameEn: 'Red LED',
                qty: 2,
            },
            {
                id: 'ledg',
                image: '/components/led-green.svg',
                nameKa: 'მწვანე შუქდიოდი',
                nameEn: 'Green LED',
                qty: 2,
                badge: '#43d9a2',
            },
            {
                id: 'ledb',
                image: '/components/led-blue.svg',
                nameKa: 'ლურჯი შუქდიოდი',
                nameEn: 'Blue LED',
                qty: 2,
                badge: '#60c5f1',
            },
            {
                id: 'q1',
                image: '/components/npn-q1.svg',
                label: 'Q1',
                nameKa: 'ტრანზისტორი NPN',
                nameEn: 'Transistor NPN',
                qty: 2,
                detailKa: 'გაძლიერების კოეფიციენტი\n100 - 200',
                detailEn: 'Current gain\n100 - 200',
            },
            {
                id: 'q2',
                image: '/components/pnp-q2.svg',
                label: 'Q2',
                nameKa: 'ტრანზისტორი PNP',
                nameEn: 'Transistor PNP',
                qty: 2,
                badge: '#43d9a2',
                detailKa: 'გაძლიერების კოეფიციენტი\n100 - 200',
                detailEn: 'Current gain\n100 - 200',
            },
            {
                id: 'q3',
                image: '/components/npn-q3.svg',
                label: 'Q3',
                nameKa: 'ტრანზისტორი NPN',
                nameEn: 'Transistor NPN',
                subtitleKa: 'დარლინგტონის წყვილი',
                subtitleEn: 'Darlington pair',
                detailKa: 'გაძლიერების კოეფიციენტი\n3000 - 10000',
                detailEn: 'Current gain\n3000 - 10000',
            },
            {
                id: 'q4',
                image: '/components/pnp-q4.svg',
                label: 'Q4',
                nameKa: 'ტრანზისტორი PNP',
                nameEn: 'Transistor PNP',
                subtitleKa: 'დარლინგტონის წყვილი',
                subtitleEn: 'Darlington pair',
                badge: '#43d9a2',
                detailKa: 'გაძლიერების კოეფიციენტი\n3000 - 10000',
                detailEn: 'Current gain\n3000 - 10000',
            },
        ],
    },
    {
        id: 'loads',
        accent: '#85d4f7',
        titleKa: 'დატვირთვები',
        titleEn: 'Loads',
        descKa: 'ნათურა და ძრავი — წრედის ხილული შედეგი.',
        descEn: 'Lamp and motor — the visible result of your circuit.',
        items: [
            {
                id: 'lamp',
                image: '/components/lamp.svg',
                nameKa: 'ნათურა',
                nameEn: 'Lamp',
            },
            {
                id: 'motor',
                image: '/components/motor.svg',
                nameKa: 'ძრავი',
                nameEn: 'Motor',
            },
        ],
    },
];
